[versions]
"3.2" = "C:\\Users\\matth\\.cobols\\gnucobol-3.2"
"2.2" = "C:\\Users\\matth\\.cobols\\gnucobol-2.2"
"2.2-b" = "C:\\Users\\matth\\.cobols\\gnucobol-2.2-b"
"1.1-open" = "C:\\Users\\matth\\.cobols\\gnucobol-1.1-open"
"1.1-gnu" = "C:\\Users\\matth\\.cobols\\gnucobol-1.1-gnu"
"3.1.2" = "C:\\Users\\matth\\.cobols\\gnucobol-3.1.2"

[project]
gnucobol = "3.2"

[packages]
"name" = { version="1.2.3", url="github.com/matthewdeanmartin/mainframer" }